use_frameworks!
platform :ios, '10.0'

target 'MYPMarkdownEditor_Example' do
  pod 'MYPMarkdownEditor', :path => '../'

  target 'MYPMarkdownEditor_Tests' do
    inherit! :search_paths

    
  end
end
